# https://hub.docker.com/_/microsoft-dotnet-core
#FROM mcr.microsoft.com/dotnet/aspnet:5.0-windowsservercore-ltsc2019 as base
FROM mcr.microsoft.com/dotnet/aspnet:3.1-nanoserver-1809 as base

WORKDIR /app
COPY list.cmd ./
ENTRYPOINT ["list.cmd"]