apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    tenantId: ""                 # the tenant ID of the KeyVault
    keyvaultName: ""             # the name of the KeyVault
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    cloudName: ""
    cloudEnvFileName: ""
    objects:  |
      array:
        - |
          objectName: aks-https
          objectAlias: https.pfx
          objectType: secret        # object types: secret, key or cert
          objectFormat: pfx         # for .NET we want the PFX format
          objectEncoding: base64    # configure the provider to decode the base64 content so we get a binary PFX
          objectVersion: ""         # [OPTIONAL] object version, default to latest if empty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-keyvault-aspnetcore-win
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-keyvault-aspnetcore-win-pod
  template:
    metadata:
      labels:
        app: aks-keyvault-aspnetcore-win-pod
    spec:
      nodeSelector:
        # ensure this deployment is scheduled on Windows nodes
        "beta.kubernetes.io/os": windows
      containers:
      - name: aks-keyvault-aspnetcore-win-pod
        image: "[YOUR-ACR-NAME].azurecr.io/aspnet-keyvault-win"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: HTTPS_CERTIFICATE_PATH
          value: "C:\\certs\\https.pfx"
        volumeMounts:
        - name: aks-keyvault-aspnetcore-win-httpscert
          mountPath: /certs
          readOnly: true
        resources:
          requests:
            cpu: 500m
          limits:
            memory: 500Mi
            cpu: 1
      volumes:
      - name: aks-keyvault-aspnetcore-win-httpscert
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
          nodePublishSecretRef:
            name: kvcreds
---
apiVersion: v1
kind: Service
metadata:
  name: aks-keyvault-aspnetcore-win-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: aks-keyvault-aspnetcore-win-pod
